version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: System.Net.Http
    versions:
    - 4.3.2
  - dependency-name: System.Text.Encodings.Web
    versions:
    - 4.3.1
